[pytest]
minversion = 9.0
addopts = --cov=src/abdp --cov-branch --cov-report=term-missing
testpaths = tests
pythonpath =
    src
    .
strict_config = True
strict_markers = True
xfail_strict = True
console_output_style = progress
